### ISSUE TITLE
 Implement Like Feature for Recipes

### ISSUE THREAD

**Issue by smrutiranjanbhuyan** [AlfiyaSiddique/TastyTrails#69] opened 2024-10-04 12:08 UTC
I want to implement a like feature for the recipe cards . This feature will allow users to like recipes, and the number of likes will be displayed on the recipe card.

**Comment by smrutiranjanbhuyan** [comment] 2024-10-04 12:09
@AlfiyaSiddique   I would like to take on this issue to implement the like feature for the recipe cards.

**Comment by AlfiyaSiddique** [comment] 2024-10-04 18:14
Duplicate of  #6

**Closed** 2024-10-04 18:14 UTC
Labels: duplicate
