### ISSUE TITLE
FEATURE: Light and Dark Mode

### ISSUE THREAD

**Issue by Dhruv-Gaba** [AlfiyaSiddique/TastyTrails#134] opened 2024-10-08 12:20 UTC
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I would like the light and dark modes to the website.

### Component

will implement it in the entire website

### It should be implemented because

Adding light and dark mode to a website enhances user experience by:

Reducing Eye Strain: Dark mode is easier on the eyes in low-light environments, minimizing fatigue, while light mode works better in bright settings.

Personalization: Users can customize their interface based on preference, improving satisfaction.

Battery Efficiency: On OLED/AMOLED screens, dark mode conserves battery life by using less power.

Aesthetic Appeal: Dark mode offers a sleek, modern look, while light mode maintains a clean, professional appearance.

Accessibility: It helps users with visual impairments or light sensitivity by making content more readable.

Auto-Switch: Time-based switching provides seamless transitions between modes for comfort.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment] 2024-10-09 18:33
duplicate of #115

**Closed by AlfiyaSiddique** 2024-10-09 18:33 UTC
Labels: enhancement, gssoc-ext, hacktoberfest-accepted
