### ISSUE TITLE
Improve Footer Design and Responsiveness

### ISSUE THREAD

**Issue by GitWizzz** [AlfiyaSiddique/TastyTrails#19] opened 2024-10-02 08:14 UTC
The current layout lacks a footer, which affects the overall design and usability. Without a footer, users miss out on quick access to essential links, social media icons, and contact information. Additionally, adding a footer will enhance the site's professionalism and structure.

**Comment by AlfiyaSiddique** [comment] 2024-10-02 13:31
Duplicate of #15

**Comment by AlfiyaSiddique** [comment] 2024-10-02 13:31
Closing this off

**Closed** 2024-10-02 13:31 UTC
Labels: duplicate
