### ISSUE TITLE
ENHANCEMENT: UPDATE README

### ISSUE THREAD

**Issue by nishant4500** [AlfiyaSiddique/TastyTrails#161] opened 2024-10-10 16:28 UTC
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

I WANT THAT IF ANY PERSON WANT TO CONTRIBUTE IN IT HOW HE OR SHE CAN LIKE WHAT IS THE PROCESS I WANT TO ADD IN THE README WHICH IS NOT IN YOUR README RIGHT NOW

### Component

README 

### It should be implemented because

EASY FOR ANY VIEWER

### Would you like to work on this issue?

None

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment] 2024-10-10 18:06
Okay @nishant4500 go ahead, but no need to add the local setup part as it is already present.

**Comment by AlfiyaSiddique** [comment] 2024-10-10 18:08
Some Important points to mention:
1. Issues are assigned based on first come first server.
2. Any change related to the design of the website needs a design proposal or reference first.
3. Please raise Prs only if the issue is assigned to you.
4. Please start working on the issue only after it is assigned to you.

Rest you can add more if you have any points in mind.

**Closed** 2024-10-11 14:41 UTC
Labels: enhancement, gssoc-ext, hacktoberfest-accepted

**Comment by nishant4500** [comment] 2024-10-11 14:45
level?
