### ISSUE TITLE
Issue:Add the hover effect over the meal cards

### ISSUE THREAD

**Issue by Hh440** [AlfiyaSiddique/TastyTrails#53] opened 2024-10-03 06:06 UTC
This effects will give them floating type view.

**Comment by Hh440** [comment] 2024-10-03 06:14
https://github.com/user-attachments/assets/0fd20ef8-7843-42c7-9320-61321662ce9c

this is how the effect will look like and same effect can be applied for small card

**Comment by AlfiyaSiddique** [comment] 2024-10-04 18:09
Duplicate of #46

**Comment by AlfiyaSiddique** [comment] 2024-10-04 18:10
@Hh440 Please look for other issues, this is already taken

**Closed** 2024-10-04 18:11 UTC
Labels: duplicate
