### ISSUE TITLE
BUG: Auto redirect to the profile page

### ISSUE THREAD

**Issue by sadath2001** [AlfiyaSiddique/TastyTrails#124] opened 2024-10-07 17:05 UTC
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe your issue

When i click on the navbar icon, tasytrails, it directs me to my user page automatically in some time

https://github.com/user-attachments/assets/3b878ded-5a4e-42d1-9930-f33b2cf59d07

### Steps to reproduce

1. Login
2. Goto main page and click on Tastytrials on navbar
3. Wait for 2 seconds
4. Itll take you to user  profile automatically

### What was the expected result?

It shouldve stayed there rather than redirecting me to the user page

### Proposed solution

Perhaps it might have something to do with navigator, should take a look once

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by geetanjalidubey9** [comment] 2024-10-07 18:03
pls assign this task to me

**Comment by AlfiyaSiddique** [comment] 2024-10-08 10:22
@sadath2001 this is not a bug but the expected feature due to session implementation.
But it does need some improvement, these are as follows:
when user clicks on TastyTrails it should navigate to home page but since the user is logged in the navbar on top must not have a login button and it should replace with profile icon. When click on profile icon it should navigate to the user profile.

Let me know if you are up for this?

**Comment by sadath2001** [comment] 2024-10-08 11:18
hi @AlfiyaSiddique , i dont think i understood.
May be you are referring to logout button? instead of login button?

Heres my understanding,

I click on tastytrails
i should just see the profile icon and not the signup button
however when i go to profile, i should be able to see the signup button correct?

**Comment by sadath2001** [comment] 2024-10-08 13:31
Alright, got it.

**Comment by AlfiyaSiddique** [comment] 2024-10-09 18:30
Okay assigning to you

**Comment by sadath2001** [comment] 2024-10-09 19:15
![image](https://github.com/user-attachments/assets/a7823437-ec24-49d4-8bfa-2ea1a32e874e)
Hi @AlfiyaSiddique , i guess this issue was linked with the pagination error,
its no longer there as i could see.

**Comment by sadath2001** [comment] 2024-10-10 11:33
hi @AlfiyaSiddique , here is my explanation again, could you please check once? i guess there was a slight misunderstanding

This is what i want to fix.

https://github.com/user-attachments/assets/8b036864-e529-4a2a-b6e3-b9d85de7bc86

**Comment by AlfiyaSiddique** [comment] 2024-10-10 15:59
@sadath2001 whatever I understood from the video I think my explanation is the same as before. The  home page is redirecting to the profile page again and again because the logic is written as follows: if the localstorage does not stores a login token stay on the home page else redirect to profile page. So when a user is logged, the local storage has a token that's why the home page is redirecting to profile page even when clicked on TastyTrails text .

**Comment by AlfiyaSiddique** [comment] 2024-10-10 15:59
Let me know if I get the issue correct that you are trying to solve and did you get what I am trying to convey.

**Comment by AlfiyaSiddique** [comment] 2024-10-10 16:01
It is not a bug and expected to be that way. But it does needs improvement that I mention here: 
https://github.com/AlfiyaSiddique/TastyTrails/issues/124#issuecomment-2399456271

**Comment by AlfiyaSiddique** [comment] 2024-10-10 16:04
I See that now the navbar is as expected as it should be on home page when the user is logged in.
The only improvement needed is to make the home page stay, now I got you @sadath2001 .
Go ahead, assigning to you.

**Closed** 2024-10-11 22:03 UTC
Labels: gssoc-ext, hacktoberfest-accepted
